project:
  type: book

book:
  title: "Theoretical Computer Science"
  author: "Igor Dimitrov"
  date: "5/17/2024"
  chapters:
    - index.qmd
    - reading.qmd
  page-navigation: true


# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

number-depth: 1
toc-depth: 4
